FROM node:20-bullseye

WORKDIR /work

# Install Java runtime (needed for Allure)
RUN apt-get update && apt-get install -y --no-install-recommends \
  default-jre \
  && rm -rf /var/lib/apt/lists/*

# Install allure CLI
RUN npm i -g allure-commandline

CMD ["bash"]
